# key-value pairs
app: user-authentication
port: 9000
version: 1.7

# comment here 

# objects

#name object
microservice:
# properties
  app: user-authentication
  port: 9000
  version: 1.7

# lists
microservices:
## (-) meaning list
  - app: user-authentication
    port: 9000
    version: 1.7

# Booleans
microservice_news:
  - app: user-authentication
    port: 9000
    version: 1.7
    # true/false , on/off, yes/no
    # YAML have 3 expression show booleans
    deployed: true

# more about list
microservice_more_lists:
  - app: user-authentication
    port: 9000
    version: 1.7
    # true/false , on/off, yes/no
    # YAML have 3 expression show booleans
    deployed: true
  - app: shopping-cart
    port: [9002, 9004, 9006]
    versions: 
    - 1.9
    - 2.0
    - 2.1
    # true/false , on/off, yes/no
    # YAML have 3 expression show booleans
    deployed: false

# multi line strings
## (|) meaning multi line
multilineString: |
  this is a multiline string
  and this is the next line
  next line

#single line string
## (>) meaning single line
singlelineString: >
  this is a single line string,
  that should be all on one line.
  some other stuff

# environment variable
# $
command:
  - /bin/sh
  - -ec
  - >-
    mysql -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'

# placeholders
apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.service.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}

# multiple yaml documents

---

# placeholders
apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.service.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}


